services:

  orders-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=orders
      - POSTGRES_USER=orders
      - POSTGRES_PASSWORD=orders
    ports:
      - "5433:5432"

  inventory-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_USER=inventory
      - POSTGRES_PASSWORD=inventory
    ports:
      - "5434:5432"

  payments-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_USER=payments
      - POSTGRES_PASSWORD=payments
    ports:
      - "5435:5432"

  inventory-service:
    build:
      context: ./inventory-service
    depends_on:
      - inventory-db
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://inventory-db:5432/inventory
      - SPRING_DATASOURCE_USERNAME=inventory
      - SPRING_DATASOURCE_PASSWORD=inventory
      - APP_SQS_ENABLED=false
    ports:
      - "8082:8082"

  payment-service:
    build:
      context: ./payment-service
    depends_on:
      - payments-db
    environment:
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payments-db:5432/payments
      - SPRING_DATASOURCE_USERNAME=payments
      - SPRING_DATASOURCE_PASSWORD=payments
      - APP_SQS_ENABLED=false
    ports:
      - "8083:8083"

  order-service:
    build:
      context: ./order-service
    depends_on:
      - orders-db
      - inventory-service
      - payment-service
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://orders-db:5432/orders
      - SPRING_DATASOURCE_USERNAME=orders
      - SPRING_DATASOURCE_PASSWORD=orders
      - APP_SQS_ENABLED=false
      - INVENTORY_BASE_URL=http://inventory-service:8082
      - PAYMENT_BASE_URL=http://payment-service:8083
      - JWT_SECRET=dev-secret-change-me-please-use-at-least-32-bytes
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8081:8081"

  web-ui:
    build:
      context: ./web-ui
    depends_on:
      - order-service
    ports:
      - "5173:80"

